# numpy tutorial

In [1]:
import numpy as np


In [2]:
myarray=np.array([1,2,3,4,5,6,7])

In [3]:
myarray

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
# converting list into array

list=[1,2,3,4]
print(list)
print(type(list))
print()
array=np.array(list)
print(array)
type(array)

[1, 2, 3, 4]
<class 'list'>

[1 2 3 4]


numpy.ndarray

In [5]:
# if list contains character then character array is form
list=[1,2,'a']
array=np.array(list)
print(array)
print(array.dtype)

['1' '2' 'a']
<U11


In [6]:
array1=np.array([1,2,3,4])
array2=np.array([[1,2,3],[4,5,6]])
print(type(array1))
print(array1.ndim)
print(array2.ndim)

<class 'numpy.ndarray'>
1
2


In [7]:
print(array1.shape)
print(array1.size)
print(array1.dtype)
print()
print(array2.shape)
print(array2.size)
print(array2.dtype)

(4,)
4
int32

(2, 3)
6
int32


In [8]:
zeros = np.zeros((3,5))

In [9]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
ones=np.ones((6,3))

In [11]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# reshaping the array


In [12]:
np.random.random((3,3))

array([[0.52187517, 0.86557363, 0.63440734],
       [0.0641848 , 0.56504995, 0.45720305],
       [0.8155247 , 0.15529575, 0.89717772]])

In [13]:
if np.random.random()>0.5:
    print("function run")
else:
    print("function not run")

function run


In [14]:
# generate function in sequence
# last parameter denotes distance
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# last parameter denotes number of values

np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [16]:
array=np.random.random((3,4))
array

array([[0.44437869, 0.9707345 , 0.7382059 , 0.84450255],
       [0.49607043, 0.14117327, 0.56945186, 0.22079191],
       [0.50833788, 0.82839194, 0.75368019, 0.47528269]])

In [17]:
array=np.reshape(array,(1,12))
array

array([[0.44437869, 0.9707345 , 0.7382059 , 0.84450255, 0.49607043,
        0.14117327, 0.56945186, 0.22079191, 0.50833788, 0.82839194,
        0.75368019, 0.47528269]])

# ARITHMETIC OPERATION


In [18]:
array=np.array([1,2,3,4,5,6])

In [19]:
array

array([1, 2, 3, 4, 5, 6])

In [20]:
#  adding umber to all elements
array+1

array([2, 3, 4, 5, 6, 7])

In [21]:
array-1

array([0, 1, 2, 3, 4, 5])

In [22]:
array*5

array([ 5, 10, 15, 20, 25, 30])

In [23]:
array/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

In [24]:
array**2

array([ 1,  4,  9, 16, 25, 36])

In [25]:
array[0]

1

In [26]:
array.max()

6

In [27]:
array.min()

1

In [28]:
array1=np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

In [29]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array1.min()

1

In [31]:
array1.max()

9

In [32]:
# axis=0  use for column wise
# axis=1 use for row wise
print(array1.min(axis=0))

array1.min(axis=1)

[1 2 3]


array([1, 4, 7])

# ARITHMETIC OPERATIONS ON TWO ARRAY


In [33]:
array1=np.array([[1,2,3],
             [3,4,5],
             [6,7,8]])
array2=np.array([[9,10,11],
                [12,13,14],
                [15,16,17]])

In [34]:
array1+array2

array([[10, 12, 14],
       [15, 17, 19],
       [21, 23, 25]])

In [35]:
array1*array2

array([[  9,  20,  33],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [36]:
array1.dot(array2)

array([[ 78,  84,  90],
       [150, 162, 174],
       [258, 279, 300]])

In [37]:
array=np.array([10,20,30,40,50,60,70,80,90,100])

In [38]:
array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [39]:
array[:]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [40]:
# elements from first to 5
array[:5]

array([10, 20, 30, 40, 50])

In [41]:
# all element except first two elements
array[2:]

array([ 30,  40,  50,  60,  70,  80,  90, 100])

In [42]:
array[-1:]

array([100])

In [43]:
array[:-2]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [44]:
# implementing on multidimension array
array1[:,:]

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
# all row and column is one
array1[:,:1]

array([[1],
       [3],
       [6]])

In [46]:
# all column row 1
array1[:1,:]

array([[1, 2, 3]])

# Array Sorting


In [47]:
array=np.array([[9,8,7,6,5,4],[7,4,1,2,5,8],[9,6,3,2,5,8]])

In [48]:
array

array([[9, 8, 7, 6, 5, 4],
       [7, 4, 1, 2, 5, 8],
       [9, 6, 3, 2, 5, 8]])

In [49]:
np.sort(array,axis=1,kind="mergsort")

array([[4, 5, 6, 7, 8, 9],
       [1, 2, 4, 5, 7, 8],
       [2, 3, 5, 6, 8, 9]])

In [50]:
np.sort(array,axis=0,kind="mergsort")

array([[7, 4, 1, 2, 5, 4],
       [9, 6, 3, 2, 5, 8],
       [9, 8, 7, 6, 5, 8]])

# ARRAY MERGING

In [51]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2=np.array([[10,9,8,7,6],[5,4,3,2,1]])

In [52]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [54]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [55]:
np.vstack((arr2,arr1))

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5, 10,  9,  8,  7,  6],
       [ 6,  7,  8,  9, 10,  5,  4,  3,  2,  1]])

In [57]:
np.hstack((arr2,arr1))

array([[10,  9,  8,  7,  6,  1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1,  6,  7,  8,  9, 10]])

In [58]:
Arr=np.concatenate((arr1,arr2),axis=0)

In [59]:
 arr= np.concatenate((arr1,arr2),axis=1)

In [60]:
arr

array([[ 1,  2,  3,  4,  5, 10,  9,  8,  7,  6],
       [ 6,  7,  8,  9, 10,  5,  4,  3,  2,  1]])

In [61]:
np.vsplit(Arr,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[10,  9,  8,  7,  6],
        [ 5,  4,  3,  2,  1]])]

In [62]:
np.hsplit(arr,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[10,  9,  8,  7,  6],
        [ 5,  4,  3,  2,  1]])]

# SLICING

In [63]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[0]

1

In [66]:
# accessing elements from given index to last index
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [67]:
# accessing elements from starting to given range
arr[:3]

array([1, 2, 3])

In [68]:
# starting to last 3 elemnts
arr[:-3]

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
arr[3:-3]

array([4, 5, 6, 7])

In [70]:
arr= np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [71]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [72]:
arr[1:,:]

array([[5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [73]:
arr[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
arr[:,1:]

array([[2, 3, 4],
       [6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

In [75]:
arr[:,:3]

array([[1, 2, 3],
       [5, 6, 7],
       [8, 7, 6],
       [4, 3, 2]])

In [77]:
#  how to access 7,8
#                6,5

arr[1:3,2:4]

array([[7, 8],
       [6, 5]])

# automating numpy

In [88]:
lst=[1,2,3,4,5,6,8,9,10]
# write a program to count number greater than 5
count=0
for i in lst:
    if (i>5):
        count+=1
print(count)

4


In [90]:
lst=np.array([1,2,3,4,5,6,7,8,9,10])

In [91]:
lst>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [92]:
lst[lst>5]

array([ 6,  7,  8,  9, 10])

In [93]:
len(lst[lst>5])

5

In [95]:
# write a program to check number divisible by 3
Lst=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
Lst%3==0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [96]:
Lst[Lst%3==0]

array([ 3,  6,  9, 12, 15, 18])